### ISSUE TITLE
Improve + New customer modal on https://app.papercups.io/customers page

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#765] opened 2021-04-21 20:17 UTC
**Problem**
Right now when creating a customer to add notes or tags you have to create and then click into the individual customer. That is a lot of clicks. 

**Solution**
We should be able to add notes and tags in side of "Create new customer" modal

**Comment by reichert621** [comment] 2021-04-23 14:31
duplicate of https://github.com/papercups-io/papercups/issues/739

**Closed by reichert621** 2021-04-23 14:31 UTC
Labels: enhancement, good first issue
