### ISSUE TITLE
Add transactions during account creation

### ISSUE THREAD

**Issue by cheeseblubber** [papercups-io/papercups#87] opened 2020-08-06 00:50 UTC
During account creation we first create the account then the user. If the user creation fails then you will have an account thats created without a user attached.

Repro:
Register for account
Enter mismatch passwords or empty fields

There would be a new account created in the table but no users associated.

**Comment by reichert621** [comment] 2020-08-06 03:31
a bit more info: the issue is in this method https://github.com/papercups-io/papercups/blob/master/lib/chat_api_web/controllers/registration_controller.ex#L38-L43

note that the account will be created even if the user creation fails -- this is what needs to be fixed

**Comment by kolharsam** [comment] 2020-08-09 18:10
@cheeseblubber @reichert621 Is this issue taken, if not then I'd like to take this up :-)

**Comment by cheeseblubber** [comment] 2020-08-09 23:38
@kolharsam definitely open we'll hold off on working on it. we'd be happy to take a pull request!

**Comment by kolharsam** [comment] 2020-08-10 05:44
@cheeseblubber I'm a beginning to learn elixir, so I hope this is not an urgent requirement, if it is, then I don't mind taking up another task

**Comment by reichert621** [comment] 2020-08-10 14:15
@kolharsam it's not too urgent :) you'll probably want to use something like this: https://hexdocs.pm/ecto/Ecto.Multi.html

let us know if you need any help!

**Comment by kolharsam** [comment] 2020-08-15 17:59
Hi @reichert621, @cheeseblubber this is what I have done so far:

```elixir

  def create_user_transaction(user_params) do
    Multi.new()
    |> Multi.run(:account, fn _, () -> do
      {:ok, account} = ChatApi.Accounts.create_account(%{company_name: user_params["company_name"]})
      if :ok
        account
      end
    end)
    |> Multi.insert(:created_user, Pow.Plug.create_user(Enum.into(user_params, %{"account_id" => :account.id})))
  end

  def create(conn, %{"user" => user_params}) do
    conn
    |> Repo.Transaction(ChatApiWeb.RegistrationController.create_user_transaction(user_params))             # this is an error
    |> case {:ok, %{account: _account, created_user: _created_user}} do
      # TODO: make changes here, since the result would be a different tuple
      {:ok, _user, conn} ->
        send_api_token(conn)

      {:error, changeset, conn} ->
        errors = Changeset.traverse_errors(changeset, &ErrorHelpers.translate_error/1)
        send_user_create_errors(conn, errors)
    end
  end

```

Am I heading in the right direction? Could I get some feedback on this?

**Comment by reichert621** [comment] 2020-08-16 20:21
hey @kolharsam — I'm a bit busy today, but let me take a look at this tomorrow :) sorry for the delay!

**Comment by reichert621** [comment] 2020-08-18 03:11
@kolharsam I'm also new to `Ecto.Multi`, but I gave it a shot like this: 
https://github.com/papercups-io/papercups/pull/167/files

basically my transactions looks like:
```ex
def user_with_account_transaction(conn, params) do
  Ecto.Multi.new()
  |> Ecto.Multi.run(:account, fn _repo, %{} ->
    ChatApi.Accounts.create_account(%{company_name: params["company_name"]})
  end)
  |> Ecto.Multi.run(:conn, fn _repo, %{account: account} ->
    user = Enum.into(params, %{"account_id" => account.id})

    case Pow.Plug.create_user(conn, user) do
      {:ok, _user, conn} -> {:ok, conn}
      {:error, reason, _conn} -> {:error, reason}
    end
  end)
end
```

I'm honestly not sure if this is the "best" way to do it, but it seems to work! 😛 (hopefully that helps)

**Comment by kolharsam** [comment] 2020-08-18 11:47
Since you've already made a PR for this, do I have anything to do?
If there's not much to do, could you point me to any other issue that might need work?

**Comment by reichert621** [comment] 2020-08-18 13:12
you could still test it out and set up a PR for it and I'd be happy to merge yours instead of mine! 

otherwise in terms of other issues, do you have a preference between backend vs frontend?

**Comment by kolharsam** [comment] 2020-08-18 14:06
Now, that you've already made a PR I can help you test and move on with this :)

and I would prefer backend :)

**Comment by kolharsam** [comment] 2020-08-27 19:28
@reichert621 I think you can close this right? PR https://github.com/papercups-io/papercups/pull/167 resolved this, right?

**Comment by reichert621** [comment] 2020-08-27 19:47
yup I'll close this now! we've been a bit busy with improvements on the chat widget + slack integration, so i'm not sure which backend tasks would be best to tackle at the moment 🤔 but if you see any issues that look interesting to you, let me know!

**Closed by reichert621** 2020-08-27 19:47 UTC
Labels: bug, good first issue
